# -*- coding: utf-8 -*-
"""Health & Wellbeing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14R-ESx96VDHkKv1WZyESQXQiNQFoJ-lF
"""

pip install streamlit pandas sentence-transformers scikit-learn

# Libraries
import json
import streamlit as st
from dataclasses import dataclass
from datetime import datetime
from functools import lru_cache
from typing import Dict, List
import random
import time

# CONFIGURATION
# We are running in DEMO MODE (No API Key required)
SCENE_NAME = "health_chat_demo"

# --- EMBEDDED DATA ---
RAW_DATA = [
  {
    "id": "malaria_symptoms_en",
    "topic": "malaria",
    "language": "en",
    "title": "Recognising Malaria Symptoms",
    "content": "Malaria often begins with fever, chills, and headache within 10–15 days after the bite of an infected mosquito. Severe malaria is an emergency: look for fainting, breathing problems, repeated convulsions, or dark urine and seek urgent care.",
    "source": { "name": "WHO Malaria Fact Sheet", "url": "https://www.who.int/news-room/fact-sheets/detail/malaria" }
  },
  {
    "id": "malaria_prevention_en",
    "topic": "malaria",
    "language": "en",
    "title": "Preventing Malaria",
    "content": "Sleep under insecticide-treated nets, use repellents with DEET, IR3535 or Icaridin, and wear long clothing after dusk. Travellers should consult health workers about preventive medicines before entering malaria areas.",
    "source": { "name": "WHO Malaria Fact Sheet", "url": "https://www.who.int/news-room/fact-sheets/detail/malaria" }
  },
  {
    "id": "cholera_signs_en",
    "topic": "cholera",
    "language": "en",
    "title": "Cholera Warning Signs",
    "content": "Cholera causes sudden, profuse watery diarrhoea and vomiting that can lead to life-threatening dehydration within hours. Seek immediate treatment if diarrhoea is accompanied by thirst, sunken eyes, or little urine output.",
    "source": { "name": "WHO Cholera Fact Sheet", "url": "https://www.who.int/news-room/fact-sheets/detail/cholera" }
  },
  {
    "id": "cholera_prevention_en",
    "topic": "cholera",
    "language": "en",
    "title": "Preventing Cholera",
    "content": "Drink safe treated water, wash hands with soap after using the toilet and before preparing food, and cook meals thoroughly. Oral cholera vaccines add protection but must be combined with water, sanitation and hygiene improvements.",
    "source": { "name": "WHO Cholera Fact Sheet", "url": "https://www.who.int/news-room/fact-sheets/detail/cholera" }
  },
  {
    "id": "nutrition_healthy_diet_en",
    "topic": "nutrition",
    "language": "en",
    "title": "Building a Healthy Plate",
    "content": "Fill meals with a variety of fruits, vegetables, whole grains, legumes, and nuts. Choose lean animal proteins or plant proteins and limit highly processed foods high in salt, sugar, and saturated fat.",
    "source": { "name": "WHO Healthy Diet Fact Sheet", "url": "https://www.who.int/news-room/fact-sheets/detail/healthy-diet" }
  },
  {
    "id": "mental_health_support_en",
    "topic": "mental_health",
    "language": "en",
    "title": "Seeking Mental Health Support",
    "content": "Mental health conditions are common and treatable. Reach out to trusted people, talk with community health workers, and access counselling or medications when recommended. Early support prevents crises.",
    "source": { "name": "WHO Mental Health Fact Sheet", "url": "https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response" }
  },
  # Adding Spanish and French samples for demo purposes
  {
    "id": "malaria_symptoms_es",
    "topic": "malaria",
    "language": "es",
    "title": "Reconocer los síntomas de la malaria",
    "content": "La malaria suele comenzar con fiebre, escalofríos y dolor de cabeza. La malaria grave es una emergencia: busque atención urgente ante desmayos o convulsiones.",
    "source": { "name": "WHO Malaria Fact Sheet", "url": "https://www.who.int/news-room/fact-sheets/detail/malaria" }
  },
  {
    "id": "malaria_symptoms_fr",
    "topic": "malaria",
    "language": "fr",
    "title": "Reconnaître les symptômes du paludisme",
    "content": "Le paludisme commence souvent par de la fièvre et des frissons. Le paludisme grave est une urgence : surveillez les évanouissements et consultez d'urgence.",
    "source": { "name": "WHO Malaria Fact Sheet", "url": "https://www.who.int/news-room/fact-sheets/detail/malaria" }
  }
]

@dataclass
class Passage:
    id: str
    title: str
    summary: str
    region_focus: str
    source: str
    url: str
    language: str = "en"

@dataclass
class RetrievedPassage:
    passage: Passage
    score: float

def load_corpus() -> List[Passage]:
    passages = []
    for p in RAW_DATA:
        src_obj = p.get("source", {})
        src_name = src_obj.get("name", "Unknown Source") if isinstance(src_obj, dict) else str(src_obj)
        src_url = src_obj.get("url", "") if isinstance(src_obj, dict) else ""

        passages.append(Passage(
            id=p.get("id", "unknown"),
            title=p.get("title", "No Title"),
            summary=p.get("content", ""),
            region_focus=p.get("topic", "General"),
            source=src_name,
            url=src_url,
            language=p.get("language", "en")
        ))
    return passages

def local_search(query: str, corpus: List[Passage]) -> List[RetrievedPassage]:
    """
    Simulates semantic search using keyword matching.
    This allows the app to function intelligently without an API key.
    """
    query_lower = query.lower()
    scored_items = []

    # Basic keyword scoring mechanism
    for p in corpus:
        score = 0.0

        # 1. Check for topic matches
        if p.region_focus in query_lower:
            score += 0.5

        # 2. Check for word overlap
        words = query_lower.split()
        matches = sum(1 for word in words if word in p.summary.lower() or word in p.title.lower())
        if matches > 0:
            score += (matches * 0.1)

        # 3. Language boost (simple detection)
        if "¿" in query and p.language == "es":
            score += 0.3
        elif "comment" in query_lower and p.language == "fr":
            score += 0.3
        elif p.language == "en" and not ("¿" in query or "comment" in query_lower):
            score += 0.1

        if score > 0:
            scored_items.append(RetrievedPassage(passage=p, score=score))

    # Sort by score
    scored_items.sort(key=lambda x: x.score, reverse=True)

    # If no matches found, return a random selection to show functionality
    if not scored_items:
        return [RetrievedPassage(p, 0.1) for p in corpus[:2]]

    return scored_items[:3]

def generate_local_answer(query: str, retrieved: List[RetrievedPassage]) -> str:
    """
    Simulates the AI generation step by constructing a coherent answer
    from the retrieved passages.
    """
    # Simulate "thinking" time
    time.sleep(1.5)

    if not retrieved:
        return "I couldn't find specific information on that topic in my database."

    # Construct a response based on the found documents
    top_result = retrieved[0]

    # Simple template-based response generation
    intro = "Based on the verified health guidelines:"
    if top_result.passage.language == "es":
        intro = "Basado en las guías de salud verificadas:"
    elif top_result.passage.language == "fr":
        intro = "Basé sur les directives sanitaires vérifiées :"

    combined_summary = "\n\n".join([f"• {r.passage.summary}" for r in retrieved])

    return f"{intro}\n\n{combined_summary}\n\n(Note: This is a demo response generated locally.)"

def main():
    st.set_page_config(page_title="Health Answers Copilot (Demo)", page_icon="🩺", layout="wide")

    st.title("Health Answers Copilot 🌍")
    st.caption("Verified health guidance from WHO (Demo Mode - No API Key Required)")

    with st.sidebar:
        st.success("✅ **Demo Mode Active**")
        st.info("This version simulates the AI behavior so you can present the UI and logic without external dependencies.")

    corpus = load_corpus()

    # Chat Interface
    if "messages" not in st.session_state:
        st.session_state.messages = [{"role": "assistant", "content": "Hello! I am your health assistant. Ask me about Malaria, Cholera, or Nutrition."}]

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if prompt := st.chat_input("Ask a health question..."):
        # User message
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Assistant logic
        with st.chat_message("assistant"):
            with st.spinner("Searching verified sources..."):
                # 1. Search (Simulated)
                results = local_search(prompt, corpus)

                # 2. Generate Answer (Simulated)
                response_text = generate_local_answer(prompt, results)

                st.markdown(response_text)

                # Show sources in an expander
                with st.expander("📚 View Verified Sources"):
                    for r in results:
                        st.markdown(f"**{r.passage.title}** ({r.passage.language.upper()})\n\n{r.passage.summary}\n\n[Source Link]({r.passage.url})")
                        st.divider()

        st.session_state.messages.append({"role": "assistant", "content": response_text})

if __name__ == "__main__":
    main()